/* Language and interaction regression tests; synthetic inputs and mocked speech only. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/ssy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const R=path.resolve(__dirname,'..'),BASE=process.env.LANGUAGE_TEST_URL||'http://127.0.0.1:8768',results=[],errors=[],external=[],speechRequests=[];
const test=async(name,fn)=>{try{await fn();results.push({name,status:'passed'});}catch(e){results.push({name,status:'failed',error:e.message});console.error(name+': '+e.message);}};
const hasChinese=s=>/[\u3400-\u9fff]/.test(s),noDialect=s=>assert.doesNotMatch(s,/[呢啲咩唔嘅佢啱睇]|廣東話|广东话|Cantonese answer/);
const pairs=[['R01','HK-53362','HK-53319'],['R02','HK-41421','HK-35198'],['R03','HK-41421','HK-67345'],['R04','HK-41421','HK-34921'],['R05','HK-41421','HK-43787'],['R06','HK-43787','HK-44354'],['R07','HK-43787','HK-64320'],['R08','HK-34337','HK-43890'],['R09','HK-41421','HK-53362'],['R10','HK-45575','HK-67272'],['R11','HK-43787','HK-35198'],['R12','HK-43787','HK-34921'],['R13','HK-43890','HK-41421'],['R14','HK-43787','HK-67345']];
(async()=>{fs.mkdirSync(R+'/qa',{recursive:true});const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),c=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true,serviceWorkers:'block'}),p=await c.newPage();p.setDefaultTimeout(10000);
await c.addInitScript(()=>{window.PUBLIC_DEMO=true;window.__speech={requests:[],spoken:[],starts:0};window.__holdSpeech=false;class FakeRecognition{start(){window.__speech.starts++;window.__speech.requests.push(this.lang);this.timer=setTimeout(()=>{if(window.__holdSpeech)return;const text=this.lang==='en-HK'?'Can these medicines be taken together?':this.lang==='zh-CN'?'这两种药可以一起服用吗？':'呢兩隻藥可唔可以一齊食？';this.onresult?.({results:[[{transcript:text}]]});this.onend?.();},20);}stop(){clearTimeout(this.timer);this.onend?.();}abort(){this.stop();}}window.SpeechRecognition=FakeRecognition;window.webkitSpeechRecognition=FakeRecognition;window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};speechSynthesis.getVoices=()=>[{name:'QA English',lang:'en-HK',localService:true},{name:'QA Mandarin',lang:'zh-CN',localService:true},{name:'QA Cantonese',lang:'zh-HK',localService:true}];speechSynthesis.speak=u=>window.__speech.spoken.push({text:u.text,lang:u.lang,voice:u.voice?.lang});speechSynthesis.cancel=()=>{};navigator.mediaDevices.getUserMedia=()=>Promise.reject(Error('Real microphone/camera prohibited by this test'));});
await c.route('**/*',r=>{const u=r.request().url();if(/^https?:/.test(u)&&new URL(u).origin!==new URL(BASE).origin){external.push(u);return r.abort();}if(u.endsWith('/api/tts')){speechRequests.push(JSON.parse(r.request().postData()));return r.fulfill({status:503,body:'QA capture only: no native audio generated'});}return r.continue();});p.on('pageerror',e=>errors.push(e.message));
const fresh=async(l)=>{await p.goto(BASE+(l?'/?lang='+l:'/'));await p.waitForFunction(()=>window.MedLocale&&window.ReleaseUI&&window.VoiceUI&&api?.runtime==='browser');};
const choose=async(l)=>{await p.selectOption('#language',l);await p.waitForFunction(v=>MedLocale.current===v,l);await p.waitForTimeout(30);};
const demo=async(which='duplicate')=>{await p.click('[data-case="'+which+'"]');for(const cb of await p.locator('[data-confirm]').all())await cb.check();await p.click('#check');};
await test('Default entry is English and uses English product/voice headings',async()=>{await fresh();assert.equal(await p.inputValue('#language'),'en');assert.equal(await p.getAttribute('html','lang'),'en');assert.equal(hasChinese(await p.locator('h1').innerText()),false);assert.match(await p.locator('#voice-heading').innerText(),/English/);assert.doesNotMatch(await p.locator('[data-t="subtitle"]').innerText(),/Cantonese/);});
for(const l of ['en','cmn','yue']){
 await test(l+': URL selects the language and resource links preserve it',async()=>{await fresh(l);assert.equal(await p.inputValue('#language'),l);assert.equal(await p.getAttribute('html','lang'),{en:'en',cmn:'zh-Hans',yue:'yue-Hant'}[l]);for(const a of await p.locator('#release-links a[href]:not([href^="https://github.com"])').all()){assert.equal(new URL(await a.getAttribute('href'),BASE).searchParams.get('lang'),l);}});
 await test(l+': all four demos require confirmation and produce their expected result',async()=>{for(const [name,rule] of [['duplicate','R01'],['interaction','R02'],['contra','R08'],['unknown',null]]){await p.click('[data-case="'+name+'"]');assert.equal(await p.locator('.selected-card').count(),2);assert.equal(await p.isDisabled('#check'),true);for(const cb of await p.locator('[data-confirm]').all())await cb.check();await p.click('#check');const r=await p.evaluate(()=>currentResult);assert.equal(r.totalPairs,1);assert.equal(r.clinicalSafety,'not_assessed');if(rule)assert.ok(r.alerts.some(x=>x.rule_id===rule));else assert.equal(r.status,'incomplete_check');}});
 await test(l+': all 14 clinical rule matches are language-invariant',async()=>{const actual=await p.evaluate(pairs=>pairs.map(([rule,a,b])=>({rule,found:E.check([a,b].map(id=>({id,confirmed:true,route:id==='HK-67272'?'sublingual':'oral'})),D).alerts.map(x=>x.rule_id)})),pairs);for(const a of actual)assert.deepEqual(a.found,[a.rule]);});
 await test(l+': manual catalogue search remains available',async()=>{await p.click('#clear');await p.fill('#search','HK-53362');assert.equal(await p.locator('#search-results [data-add="HK-53362"]').count(),1);await p.click('#search-results [data-add="HK-53362"]');assert.equal(await p.inputValue('[data-route="HK-53362"]'),'unknown');});
 await test(l+': knowledge shortcuts use the selected language',async()=>{for(const q of await p.locator('[data-profile-question]').all()){await q.click();const value=await p.inputValue('#question-text');if(l==='en')assert.equal(hasChinese(value),false);if(l==='cmn'){noDialect(value);assert.equal(await p.evaluate(t=>MedLocale.simplify(t),value),value);}if(l==='yue')assert.match(value,/[呢啲咩點]/);}});
 await test(l+': product details and profile audio use the selected language',async()=>{await p.click('#selected [data-product="HK-53362"]');assert.ok(await p.isVisible('#dialog'));const title=await p.locator('#dialog-title').innerText(),profile=await p.locator('.ingredient-profile').first().innerText();if(l==='en'){assert.equal(title,'Medicine details');assert.equal(hasChinese(await p.locator('.ingredient-profile h3').first().innerText()),false);assert.match(profile,/Used for pain and fever/);assert.doesNotMatch(await p.locator('[data-read-profile]').innerText(),/Cantonese/);}if(l==='cmn'){noDialect(title);assert.match(title,/药品/);}await p.evaluate(()=>window.__speech.spoken=[]);await p.click('[data-read-profile]');const spoken=await p.evaluate(()=>window.__speech.spoken.at(-1));assert.equal(spoken.lang,{en:'en-HK',cmn:'zh-CN',yue:'zh-HK'}[l]);if(l==='en')assert.equal(hasChinese(spoken.text),false);if(l==='cmn'){noDialect(spoken.text);assert.equal(await p.evaluate(t=>MedLocale.simplify(t),spoken.text),spoken.text);}const original=await p.locator('.source-links a').first().innerText();assert.equal(original,await p.evaluate(()=>D.medicineProfiles.sources.paracetamol.title));await p.click('#close-dialog');});
 await test(l+': pharmacist text download follows current language and preserves user input',async()=>{await demo();await p.locator('#consultation-fields summary').click();await p.check('[data-context="allergy"]');const raw='原話：藥袋寫「維持劑量」，請核實。';await p.fill('#context-question',raw);await p.click('#check');await p.click('#pharmacist-result');const pending=p.waitForEvent('download');await p.click('[data-export-consultation]');const d=await pending,stream=await d.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);const text=Buffer.concat(chunks).toString('utf8');assert.ok(text.includes(raw));const generated=text.replace(raw,'');if(l==='en'){assert.equal(hasChinese(generated),false);assert.match(generated,/Drug allergy/);assert.doesNotMatch(generated,/confirmed\s*\/|演示/);}if(l==='cmn'){noDialect(generated);assert.equal(await p.evaluate(t=>MedLocale.simplify(t),generated),generated);}if(l==='yue')assert.match(generated,/藥師|藥物過敏/);await p.click('#close-dialog');});
 await test(l+': recognition explicitly opts in and selects the correct language',async()=>{await p.click('#record-question');const starts=await p.evaluate(()=>window.__speech.starts);await p.click('#voice-decline');assert.equal(await p.evaluate(()=>window.__speech.starts),starts);await p.click('#record-question');await p.click('#voice-consent');await p.waitForFunction(n=>window.__speech.starts>n,starts);await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>window.__speech.requests.at(-1)),{en:'en-HK',cmn:'zh-CN',yue:'zh-HK'}[l]);assert.equal(await p.isVisible('#voice-answer'),false);await p.click('#confirm-question');assert.equal(await p.isVisible('#voice-answer'),true);const spoken=await p.evaluate(()=>window.__speech.spoken.at(-1));assert.equal(spoken.lang,{en:'en-HK',cmn:'zh-CN',yue:'zh-HK'}[l]);if(l==='en'){assert.equal(hasChinese(await p.locator('#answer-text').innerText()),false);assert.doesNotMatch(await p.locator('#voice-heading').innerText(),/Cantonese/);}if(l==='cmn')noDialect(await p.locator('#answer-text').innerText());});
 for(const width of [320,390])await test(l+': '+width+'px large-text layout has no horizontal overflow',async()=>{await fresh(l);await p.setViewportSize({width,height:844});await p.click('#large-font');await demo();const layout=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('button,input,select,textarea')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().right>innerWidth+1).map(e=>({id:e.id,text:e.textContent.slice(0,60),right:e.getBoundingClientRect().right}))}));assert.ok(layout.scroll<=layout.width,JSON.stringify(layout));assert.deepEqual(layout.controls,[]);await p.screenshot({path:R+'/qa/language-'+l+'-'+width+'.png',fullPage:true});});
}
await test('Switching languages preserves selected identities, routes, confirmations and raw question',async()=>{await fresh('yue');await demo();const raw='請保留呢句原話：藥袋劑量未明。';await p.fill('#question-text',raw);await p.locator('#consultation-fields summary').click();await p.fill('#context-question',raw);await p.fill('#search','撲熱息痛');const original=await p.evaluate(()=>JSON.stringify(selected));for(const l of ['cmn','en','yue']){await choose(l);assert.equal(await p.evaluate(()=>JSON.stringify(selected)),original);assert.equal(await p.inputValue('#question-text'),raw);assert.equal(await p.inputValue('#context-question'),raw);assert.equal(await p.inputValue('#search'),'撲熱息痛');}});
await test('Offline Mac mode disables non-Cantonese recognition and hides audio upload',async()=>{await fresh('en');await p.evaluate(()=>{window.PUBLIC_DEMO=false;api={runtime:'local',ocr:true,asr:true,tts:true,token:'qa-only'};window.dispatchEvent(new Event('local-api-ready'));});for(const l of ['en','cmn']){await choose(l);assert.equal(await p.isDisabled('#record-question'),true);assert.equal(await p.isDisabled('#voice-file'),true);assert.equal(await p.locator('label[for="voice-file"]').isVisible(),false);}await choose('yue');assert.equal(await p.isDisabled('#record-question'),false);assert.equal(await p.isDisabled('#voice-file'),false);assert.equal(await p.locator('label[for="voice-file"]').isVisible(),true);});
await test('Mac profile reading sends the selected voice without real audio generation',async()=>{for(const l of ['en','cmn','yue']){await choose(l);await p.fill('#search','HK-53362');await p.click('#search-results [data-product="HK-53362"]');const n=speechRequests.length;await p.click('[data-read-profile]');await p.waitForTimeout(80);assert.equal(speechRequests.length,n+1);assert.equal(speechRequests.at(-1).voice,l);if(l==='en')assert.equal(hasChinese(speechRequests.at(-1).text),false);if(l==='cmn')noDialect(speechRequests.at(-1).text);await p.click('#close-dialog');}});
await test('No uncaught browser exceptions or unexpected outgoing requests',()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});
const output={date:new Date().toISOString(),url:BASE,passed:results.filter(x=>x.status==='passed').length,failed:results.filter(x=>x.status==='failed').length,scope:'Language and UI behavior using synthetic cases, mocked browser speech/voices and intercepted local TTS. No real microphone, camera, cloud speech, patient testing, clinical approval or accuracy measurement. Offline cache tested separately.',results,errors,external,speech_requests:speechRequests.map(x=>({voice:x.voice,text_language_checked:true}))};fs.writeFileSync(R+'/qa/language-ui-results.json',JSON.stringify(output,null,2));await b.close();console.log(JSON.stringify({passed:output.passed,failed:output.failed,failures:results.filter(x=>x.status==='failed')},null,2));if(output.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
