'use strict';
const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const checks=[],errors=[],base=process.env.TEST_URL||'http://127.0.0.1:8769';const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const ctx=await browser.newContext({viewport:{width:390,height:844}});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));try{
await page.goto(base);await page.click('#prepare-offline');await page.waitForFunction(()=>{const s=window.OfflineRuntime?.getState();return s?.current||s?.phase==='failed'},null,{timeout:120000});const state=await page.evaluate(()=>OfflineRuntime.getState());assert.equal(state.current,true,JSON.stringify(state));checks.push('Complete current public asset set verifies before offline use');
await ctx.setOffline(true);
for(const [locale,htmlLang] of [['en','en'],['cmn','zh-Hans'],['yue','yue-Hant']]){await page.goto(base+'/?lang='+locale);assert.equal(await page.locator('html').getAttribute('lang'),htmlLang);await page.fill('#search','HK-53362');await page.waitForSelector('[data-add="HK-53362"]');await page.click('[data-case="duplicate"]');for(const box of await page.locator('[data-confirm]').all())await box.check();await page.click('#check');assert.equal(await page.locator('.alert-card').count(),1);assert.equal(await page.locator('#record-question').isDisabled(),true);checks.push(locale+': offline reopen, lookup, duplicate rule and voice-offline boundary');}
await page.locator('#photo-entry>summary').click();await page.click('#ocr-sample');await page.waitForSelector('#ocr-candidates [data-add="HK-53362"]',{timeout:90000});checks.push('Offline OCR still reads the synthetic label with the updated language bundle');
for(const name of ['offline','data-report','verify']){await page.goto(base+'/'+name+'?lang=cmn');assert.equal(await page.locator('html').getAttribute('lang'),'zh-Hans');}checks.push('Offline auxiliary routes retain Mandarin language selection');
assert.deepEqual(errors,[]);checks.push('No JavaScript exceptions');fs.writeFileSync(process.env.TEST_OUTPUT||'qa/offline-languages-results.json',JSON.stringify({date:new Date().toISOString(),url:base,passed:checks.length,checks,state,errors,scope:'Chromium mobile viewport and synthetic labels; not physical-phone or clinical validation.'},null,2));console.log(JSON.stringify({passed:checks.length,state}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
