'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),P=require('../app/patient.js'),I=require('../app/medicine-info.js'),E=require('../app/engine.js'),L=require('../app/locale.js');const box={window:{}};vm.runInNewContext(fs.readFileSync('app/data.js','utf8'),box);const D=box.window.MED_DATA,pair=['HK-53362','HK-53319'].map(id=>({id,confirmed:true})),result=E.check(pair,D),checks=[];
function test(name,run){run();checks.push(name)}
const asks={en:['Can these medicines be taken together?','Why ask a pharmacist?','How much should I take?','What are these medicines used for?','What are the side effects?','How should these be stored?'],cmn:['这两种药可以一起服用吗？','为什么要问药师？','我应该服用多少？','这些药有什么作用？','这些药有什么副作用？','这些药应该怎样存放？'],yue:['呢兩隻藥可唔可以一齊食？','點解要問藥劑師？','我應該食幾多粒？','呢啲藥有咩作用？','呢啲藥有咩副作用？','呢啲藥應該點樣存放？']};
const expected=['check_summary','pharmacist','personal_review','use_information','side_effects_information','storage_information'];
for(const locale of ['en','cmn','yue'])test(locale+' examples preserve intent, medical limits and their own language',()=>asks[locale].forEach((question,i)=>{const a=P.answer(question,pair,result,D,locale);assert.equal(a.intent,expected[i],locale+': '+question);assert.equal(a.clinicalSafety,'not_assessed');assert.deepEqual(a.autoSelect,[]);if(locale==='en')assert.doesNotMatch(a.text,/[\u3400-\u9fff]/);if(locale==='cmn'){assert.equal(L.simplify(a.text),a.text);assert.doesNotMatch(a.text,/[唔嘅喺佢咁]/);}}));
test('Every language keeps the same rule/source identities',()=>{for(let i=0;i<6;i++){const answers=['en','cmn','yue'].map(l=>P.answer(asks[l][i],pair,result,D,l));assert.deepEqual(answers[0].sourceRuleIds,answers[1].sourceRuleIds);assert.deepEqual(answers[0].sourceProfileIds,answers[2].sourceProfileIds);}});
test('English general information uses the stored English profile rather than a new medical translation',()=>{const a=I.knowledge('What are the side effects?',pair,D,'en');assert.ok(a.text.includes(D.medicineProfiles.ingredients.paracetamol.side_effects_en));});
test('Emergency, prescription and identity gates remain localized and conservative',()=>{for(const [q,intent]of [['I am having trouble breathing','urgent_help'],['My prescription and pack instructions differ','prescription_reconciliation'],['blood thinner with panadol','ambiguous_name']]){const a=P.answer(q,pair,result,D,'en');assert.equal(a.intent,intent);assert.doesNotMatch(a.text,/[\u3400-\u9fff]/);assert.equal(a.clinicalSafety,'not_assessed');}assert.match(P.answer('呼吸困难',[],null,D,'cmn').text,/999/);assert.equal(P.answer('What are the side effects?',[{id:pair[0].id,confirmed:false}],null,D,'en').intent,'identity_required');});
test('Source warnings remain distinct from no-coverage and personal prescribing',()=>{const none=E.check(['HK-44354','HK-35198'].map(id=>({id,confirmed:true})),D);assert.match(P.warningText(none,D,'en').join(' '),/does not mean/);assert.match(P.referral(null,'en').reason,/not been confirmed/);assert.doesNotMatch(P.referral(result,'cmn').question,/[唔嘅喺佢咁]/);});
test('Omitted locale retains Cantonese compatibility',()=>assert.equal(P.answer(asks.yue[0],pair,result,D).text,P.answer(asks.yue[0],pair,result,D,'yue').text));
fs.writeFileSync('qa/patient-languages-results.json',JSON.stringify({date:new Date().toISOString(),passed:checks.length,checks,clinical_validation:false},null,2));console.log(checks.length+' patient language checks passed');
