/* A team-supplied photograph, processed by the actual browser OCR engine. */
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/ssy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'block'}),base=process.env.TEST_URL||'http://127.0.0.1:8896',errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
 await page.goto(base);await page.waitForFunction(()=>api?.runtime==='browser');await page.locator('#photo-entry>summary').click();assert.equal(await page.locator('#ocr-sample').innerText(),'Sample photo 1');
 await page.click('#ocr-sample');await page.waitForSelector('#ocr-candidates [data-add="HK-28848"]',{timeout:90000});const text=await page.locator('#ocr-text').innerText();assert.match(text,/Metronidazole/i);assert.match(text,/HK[ -]*28848/);assert.equal(await page.locator('#selected .selected-card').count(),0);
 const dims=await page.locator('#ocr-preview img').evaluate(i=>[i.naturalWidth,i.naturalHeight]);assert.deepEqual(dims,[1279,1706]);await page.click('#ocr-candidates [data-add="HK-28848"]');assert.equal(await page.locator('[data-confirm]:checked').count(),0);assert.equal(await page.evaluate(()=>selected[0].sample),true);
 const local=fs.readFileSync(require('node:path').resolve(__dirname,'../app/sample-medicine.jpg')),remote=await page.request.get(base+'/sample-medicine.jpg');assert.equal(crypto.createHash('sha256').update(await remote.body()).digest('hex'),crypto.createHash('sha256').update(local).digest('hex'));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
 const report={tested_at:new Date().toISOString(),url:base,sample_sha256:crypto.createHash('sha256').update(local).digest('hex'),recognised_ingredient:'Metronidazole',recognised_registration:'HK-28848',image_dimensions:dims,automatic_selection:false,confirmation_required:true,practice_example:true,errors,outbound_writes:writes,scope:'One supplied real photo in desktop Chrome at phone width; not a general OCR accuracy or clinical study.'};if(process.env.TEST_OUTPUT)fs.writeFileSync(process.env.TEST_OUTPUT,JSON.stringify(report,null,2)+'\n');console.log('PASS real sample button, image bytes and dimensions, actual bilingual OCR, HK-28848, confirmation gate, no uploads');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
