'use strict';
const fs=require('fs'),assert=require('assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),checks=[],errors=[],tts=[];
await context.addInitScript(()=>{window.PUBLIC_DEMO=true;window.__recognitionLanguages=[];window.__spoken=[];window.__mediaRequests=0;
 window.SpeechRecognition=class{start(){window.__recognitionLanguages.push(this.lang);this.timer=setTimeout(()=>{this.onresult?.({results:[[{transcript:({'en-HK':'Can these medicines be taken together?','zh-CN':'这两种药可以一起服用吗？','zh-HK':'呢兩隻藥可唔可以一齊食？'})[this.lang]}]]});this.onend?.();},100);}stop(){clearTimeout(this.timer);this.onend?.();}abort(){clearTimeout(this.timer);this.onerror?.({error:'aborted'});this.onend?.();}};
 window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{lang:'en-GB',localService:true},{lang:'zh-CN',localService:true},{lang:'zh-HK',localService:true},{lang:'en-US',localService:false}],cancel(){},speak(u){window.__spoken.push({lang:u.lang,text:u.text,local:u.voice.localService});}}});
 navigator.mediaDevices.getUserMedia=async()=>{window.__mediaRequests++;throw Error('Unexpected physical microphone request');};});
await context.route('**/api/tts',async route=>{tts.push(route.request().postDataJSON());await route.fulfill({status:200,contentType:'audio/wav',body:Buffer.from('RIFF-invalid-test-placeholder')});});page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(process.env.TEST_URL||'http://127.0.0.1:9878');assert.equal(await page.locator('#language').inputValue(),'en');assert.match(await page.locator('[data-v=heading]').innerText(),/English/);checks.push('Default English reaches voice heading and selector');
await page.click('[data-case=duplicate]');for(const box of await page.locator('[data-confirm]').all())await box.check();await page.click('#check');
for(const [locale,tag,ttsTag,expected]of [['en','en-HK','en-GB','Can these medicines'],['cmn','zh-CN','zh-CN','这两种药'],['yue','zh-HK','zh-HK','呢兩隻藥']]){
 await page.selectOption('#language',locale);await page.click('[data-v=example1]');assert.ok((await page.inputValue('#question-text')).startsWith(expected));await page.click('#confirm-question');await page.waitForFunction(()=>window.__spoken.length>0);const last=await page.evaluate(()=>window.__spoken.at(-1));assert.equal(last.lang,ttsTag);assert.equal(last.local,true);if(locale==='en')assert.doesNotMatch(await page.locator('#answer-text').innerText(),/[\u3400-\u9fff]/);
 const count=await page.evaluate(()=>window.__recognitionLanguages.length);await page.click('#record-question');await page.waitForSelector('#voice-consent');assert.equal(await page.evaluate(()=>window.__recognitionLanguages.length),count);await page.click('#voice-consent');await page.waitForFunction(c=>window.__recognitionLanguages.length>c,count);assert.equal(await page.evaluate(()=>window.__recognitionLanguages.at(-1)),tag);await page.waitForTimeout(180);assert.ok((await page.inputValue('#question-text')).startsWith(expected));checks.push(locale+': example, answer, local speech and browser recognition language agree; consent precedes recognition');
}
await page.selectOption('#language','en');const preserved=await page.inputValue('#question-text');await page.click('#record-question');await page.waitForSelector('#voice-consent');await page.evaluate(()=>MedLocale.set('cmn'));assert.equal(await page.isVisible('#dialog'),false);assert.equal(await page.inputValue('#question-text'),preserved);checks.push('Language change cancels outstanding speech consent, clears the old answer and preserves the original question');
await context.setOffline(true);await page.evaluate(()=>VoiceUI.update());assert.equal(await page.isDisabled('#record-question'),true);const offline=await page.evaluate(async()=>{try{await BrowserRuntime.listen('en');return false;}catch{return true;}});assert.equal(offline,true);await context.setOffline(false);checks.push('Offline browser recognition remains blocked');
await page.evaluate(()=>{window.PUBLIC_DEMO=false;api={runtime:'local',asr:true,tts:true,token:'synthetic-test'};MedLocale.set('en');});await page.waitForTimeout(50);assert.equal(await page.isDisabled('#record-question'),true);assert.match(await page.locator('#voice-status').innerText(),/Cantonese only/);await page.evaluate(()=>document.querySelector('#record-question').onclick());assert.equal(await page.evaluate(()=>window.__mediaRequests),0);await page.click('[data-v=example1]');await page.click('#confirm-question');await page.waitForFunction(()=>!!document.querySelector('#answer-audio audio'));assert.equal(tts.at(-1).voice,'en');
await page.selectOption('#language','cmn');assert.equal(await page.isDisabled('#record-question'),true);await page.click('[data-v=example1]');await page.click('#confirm-question');await page.waitForTimeout(100);assert.equal(tts.at(-1).voice,'cmn');await page.selectOption('#language','yue');assert.equal(await page.isDisabled('#record-question'),false);checks.push('Mac recognition only enables Cantonese, while local reading selects English or Mandarin correctly');
assert.deepEqual(errors,[]);checks.push('No browser JavaScript exceptions');fs.writeFileSync('qa/voice-languages-browser-results.json',JSON.stringify({date:new Date().toISOString(),passed:checks.length,checks,errors,scope:'Recognition and local voices are controlled test doubles. Verifies language routing and privacy gates, not provider accuracy or real-device voice availability.'},null,2));console.log(checks.length+' voice language browser checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
