'use strict';
(()=>{const $=s=>document.querySelector(s),D=MED_DATA,V=AIOutputValidator;let truth=[],record=null,example=false,revision=0;const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const labels={catalogue_match:'本次目录字段一致',normalized_match:'显式同义词归一化后，目录字段一致',conflict:'发现与参照资料冲突，暂不采纳',unverified:'证据不足或包含未经验证的内容，暂不采纳'};
 function invalidate(){revision++;record=null;$('#export').disabled=true;$('#result-panel').hidden=true;$('#error').textContent='';}
 function load(){invalidate();$('#truth-confirm').checked=false;truth=[$('#ref-a').value.trim().toUpperCase(),$('#ref-b').value.trim().toUpperCase()].map(id=>({id,confirmed:false}));$('#reference').innerHTML=truth.map((r,i)=>{const p=D.products.find(p=>p.registration_number===r.id);return `<div class="ref"><strong>${i+1}. ${esc(p?.product_name||'目录未找到该产品')}</strong><div>${esc(r.id)}</div><div>${esc(p?.active_ingredients.join(' / ')||'需要独立核实，不推断成分')}</div></div>`}).join('');}
 function seeded(kind){$('#ref-a').value='HK-53362';$('#ref-b').value=kind==='unknown'?'HK-99999':'HK-53319';load();$('#record-kind').value='practice';$('#platform').value='人工构造的核验器测试，非小浣熊';$('#run-id').value='PRACTICE-'+kind;$('#attachments').value='';$('#untouched').checked=false;$('#prompt').value='人工构造样例。未向任何平台发送，也不是平台原始输出。';const out={products:truth.map((r,i)=>{const p=D.products.find(p=>p.registration_number===r.id);return {input_index:i+1,registration_number:r.id,product_name:p?.product_name||'UNKNOWN PRODUCT',ingredients:p?[...p.active_ingredients]:['paracetamol'],dose:null,frequency:null};})};if(kind==='alias')out.products[0].ingredients=['acetaminophen'];if(kind==='missing')out.products[1].ingredients=['paracetamol'];if(kind==='dose'){out.products[0].dose='2 tablets';out.products[0].frequency='three times daily';}$('#raw').value=JSON.stringify(out,null,2);example=true;}
 async function validate(){invalidate();const started=revision;truth.forEach(x=>x.confirmed=$('#truth-confirm').checked);const raw=$('#raw').value,kind=$('#record-kind').value;
 if(kind==='real'&&(example||!$('#untouched').checked||!$('#platform').value.trim()||!$('#run-id').value.trim()||!$('#prompt').value.trim()||!$('#attachments').value.trim())){$('#error').textContent='实际运行须保留平台、运行编号、原提示词及输入／输出附件引用，并确认未改写。加载的演练样例不能转为真实证据；请刷新页面后录入实际运行。';return;}
 let parsed,validation;try{parsed=V.parse(raw);validation=V.validate(truth,parsed,D);}catch{validation={status:'unverified',reason:'output_not_parseable_JSON',identity_accepted:false,clinical_safety:'not_assessed',rows:[]};}
 const ruleResult=validation.identity_accepted?MedEngine.check(truth,D):null;let sha=null;try{if(crypto.subtle)sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))].map(b=>b.toString(16).padStart(2,'0')).join('');}catch{}
 if(started!==revision)return;
 record={schema_version:'1.0',record_type:kind==='real'?'operator_declared_platform_run_unverified_attachments':'constructed_practice',date:new Date().toISOString(),platform:$('#platform').value,run_id:$('#run-id').value,prompt:$('#prompt').value,raw_output:raw,raw_output_sha256:sha,attachment_references:$('#attachments').value,attachments_verified:false,reference_inputs:truth.map(x=>({...x})),source_snapshot:'2026-09-25',reference_source:'https://data.gov.hk/en-data/dataset/hk-dh-dh_do-hk-dh-do-pharmaceutical-product',validation,rule_result:ruleResult,clinical_review:'pending_ella_review'};
 $('#verdict').innerHTML=`<div class="verdict ${esc(validation.status)}">${esc(labels[validation.status])}</div><p>${esc(validation.reason)}</p><p class="muted">${kind==='real'?'操作者声明为平台实际运行；附件真实性尚待人工检查。':'人工构造／演练结果，不是小浣熊实测成绩。'}</p>`;
 $('#field-results').innerHTML=(validation.rows||[]).map(r=>`<h3 class="field-heading">输入 ${r.input_index} · ${esc(r.reference_id)}</h3><table><tr><th>字段</th><th>AI 输出</th><th>独立参照</th><th>核验</th></tr>${r.checks.map(c=>`<tr><td>${esc(c.field)}</td><td>${esc(JSON.stringify(c.observed))}</td><td>${esc(JSON.stringify(c.expected))}</td><td>${esc({matched:'字段相符',conflict:'冲突',unverified:'未验证'}[c.status])}<br>${esc(c.reason)}</td></tr>`).join('')}</table>${r.normalizations?.length?'<p class="source">显式归一化：'+esc(r.normalizations.map(n=>n.observed+' → '+n.canonical).join('；'))+'。别名映射待专业复核。</p>':''}`).join('');
 $('#rule-result').innerHTML=!ruleResult?'<p>身份字段尚未通过核验，不把这份 AI 输出传入规则判断。请补证据或更正后新建记录。</p>':`<p>已独立确认产品后查询规则：${esc(ruleResult.status)}。即使未命中，也不能据此否定 AI 的药名转换，更不能认定合用安全。</p>${ruleResult.alerts.map(r=>`<p><strong>${esc(r.rule_id)}</strong> ${esc(r.summary_zh)} <a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">出处</a></p>`).join('')}<p>规则全待医学复核，未覆盖风险仍存在。</p>`;
 $('#result-panel').hidden=false;$('#export').disabled=false;
 }
 $('#load-reference').onclick=load;$('#validate').onclick=validate;$('#export').onclick=()=>{if(!record)return;const u=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='ai-validation-'+record.record_type+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);};
 document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>seeded(b.dataset.example));
 for(const id of ['#raw','#prompt','#platform','#run-id','#record-kind','#attachments','#untouched','#truth-confirm'])$(id).addEventListener('input',invalidate);
 for(const id of ['#ref-a','#ref-b'])$(id).addEventListener('input',()=>{$('#truth-confirm').checked=false;truth=[];$('#reference').textContent='输入已修改，请重新读取目录并确认。';invalidate();});
 load();
})();
