<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="drugs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lastUpdate"/>
        <xs:element maxOccurs="unbounded" ref="drug"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lastUpdate" type="xs:NMTOKEN"/>
  <xs:element name="drug">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="productName"/>
        <xs:element ref="regCertHolderName"/>
        <xs:element ref="permitNo"/>
        <xs:element ref="activeIngs"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="productName" type="xs:string"/>
  <xs:element name="regCertHolderName" type="xs:string"/>
  <xs:element name="permitNo" type="xs:NCName"/>
  <xs:element name="activeIngs">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="activeIng"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="activeIng" type="xs:string"/>
</xs:schema>
