"""Build offline browser data from the attributed source pack; Python stdlib only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'data-pack/data'
def read(name): return json.loads((DATA/name).read_text())
rules=read('demo_rules.json')
english={
 'R01':'Both products contain paracetamol. Taking both can duplicate this ingredient. Check with a pharmacist or prescriber before combining them.',
 'R02':'Warfarin with ibuprofen can increase bleeding risk. A clinician should assess the combination and monitoring needs. This warning is not an absolute ban.',
 'R03':'Warfarin with aspirin can increase bleeding risk. A clinician should assess the combination and monitoring needs. This warning is not an absolute ban.',
 'R04':'Warfarin with naproxen can increase bleeding risk. A clinician should assess the combination and monitoring needs. This warning is not an absolute ban.',
 'R05':'Warfarin with clopidogrel can increase bleeding risk. A clinician should assess the combination and monitoring needs. This warning is not an absolute ban.',
 'R06':'Omeprazole can reduce the antiplatelet effect of clopidogrel. The cited label recommends avoiding this combination. Ask the prescriber or pharmacist to review it.',
 'R07':'Esomeprazole can reduce the antiplatelet effect of clopidogrel. The cited label recommends avoiding this combination. Ask the prescriber or pharmacist to review it.',
 'R08':'The cited label contraindicates simvastatin with clarithromycin because of muscle injury and rhabdomyolysis risk. Contact the prescriber or pharmacist promptly for advice.',
 'R09':'If taking warfarin, ask a pharmacist or prescriber before using paracetamol. This is a precaution requiring individual assessment, not an absolute contraindication.',
 'R10':'Sildenafil with a nitrate such as glyceryl trinitrate can cause dangerously low blood pressure. Ask a clinician promptly to review this combination.'
}
for r in rules: r['summary_en']=english.get(r['rule_id'],r.get('summary_en',''))
excerpts={
 'hk_paracetamol':'出處摘要（非逐字引述）：含撲熱息痛的不同藥物不宜自行同時使用；服用華法林者在使用前應先徵詢醫護意見。 / Source summary: check duplicate paracetamol exposure and seek advice when taking warfarin.',
 'hk_sildenafil':'出處摘要（非逐字引述）：昔多芬與硝酸鹽類藥物一起使用可引致嚴重低血壓。 / Source summary: sildenafil with nitrates can cause severe low blood pressure.',
 'warfarin_label':'出處摘要（非逐字引述）：第 7.3 節及表 3 列出增加出血風險的藥物，涵蓋相關非類固醇消炎藥與抗血小板藥物；合用需監測。 / Section 7.3 and Table 3 discuss increased bleeding risk and monitoring.',
 'clopidogrel_label':'出處摘要（非逐字引述）：第 7.1 節建議避免與奧美拉唑或埃索美拉唑合用；第 7.2 節指出 NSAID 合用的胃腸出血風險。阿司匹林合用可屬刻意處方，出血風險及停藥風險須一併核實。 / Sections 7.1–7.2 address PPIs and NSAIDs; aspirin combinations may be prescribed and require individual review.',
 'clarithromycin_label':'出處摘要（非逐字引述）：第 4.5 節列辛伐他汀合用為禁忌；第 5.4 節及第 7 節華法林項指出出血與 INR 監測需要。 / Sections 4.5, 5.4 and 7 distinguish a simvastatin contraindication from warfarin monitoring.'
}
payload=dict(products=read('hk_products.json'),demoProducts=read('demo_products.json'),rules=rules,
             aliases=read('ingredient_aliases.json'),sources=read('rule_sources.json'),excerpts=excerpts,
             lexicon=json.loads((ROOT/'data/seed_lexicon.json').read_text()),patientWording=json.loads((ROOT/'data/patient_wording.json').read_text()),
             medicineProfiles=json.loads((ROOT/'data/medicine_profiles.json').read_text()))
(ROOT/'app/data.js').write_text('/* Generated by tools/build_data.py. Sources: data-pack/SOURCES.md */\nwindow.MED_DATA='+json.dumps(payload,ensure_ascii=False,separators=(',',':'))+';\n')
print(f"Built {len(payload['products'])} catalogue records, {len(payload['demoProducts'])} demo formulations, {len(rules)} rules")

# Keep the portable SQLite handoff aligned with the in-app education layer.
import sqlite3
with sqlite3.connect(DATA/'hk_medication.sqlite') as con:
    con.execute('CREATE TABLE IF NOT EXISTS medicine_profiles (canonical TEXT PRIMARY KEY, data_json TEXT NOT NULL)')
    con.execute('CREATE TABLE IF NOT EXISTS medicine_profile_sources (source_id TEXT PRIMARY KEY, data_json TEXT NOT NULL)')
    con.execute('CREATE TABLE IF NOT EXISTS medicine_formulation_hints (registration_number TEXT PRIMARY KEY, data_json TEXT NOT NULL)')
    for table,key in [('medicine_profiles','ingredients'),('medicine_profile_sources','sources'),('medicine_formulation_hints','formulations')]:
        con.execute('DELETE FROM '+table)
        con.executemany('INSERT INTO '+table+' VALUES (?,?)',[(k,json.dumps(v,ensure_ascii=False)) for k,v in payload['medicineProfiles'][key].items()])
print('Updated SQLite education profiles and provenance; clinical review remains pending')

with sqlite3.connect(DATA/'hk_medication.sqlite') as con:
    con.execute('CREATE TABLE IF NOT EXISTS current_rule_drafts (rule_id TEXT PRIMARY KEY, data_json TEXT NOT NULL)')
    con.execute('DELETE FROM current_rule_drafts')
    con.executemany('INSERT INTO current_rule_drafts VALUES (?,?)',[(r['rule_id'],json.dumps(r,ensure_ascii=False)) for r in rules])

with sqlite3.connect(DATA/"hk_medication.sqlite") as con:
    con.execute("DELETE FROM demo_rules")
    con.executemany("INSERT INTO demo_rules VALUES (?,?)",[(r["rule_id"],json.dumps(r,ensure_ascii=False)) for r in rules])
